runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /input
  script: main.app

libraries:
- name: numpy
  version: "1.6.1"
- name: ssl
  version: latest
- name: flask
  version: "0.12"
env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'anyvalue'